accounts/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views
from registration.backends.simple import views as registration_views

from . import views
from . import forms

app_name = 'accounts'
urlpatterns = [
    # authentication
    url(r'^login', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout', auth_views.logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^registration', registration_views.RegistrationView.as_view(
        form_class=forms.RegistrationForm
    ), name='registration'),

    # password
    url(r'^password/change/$', auth_views.password_change, {
        'template_name': 'accounts/password_change.html',
        'post_change_redirect': reverse_lazy('accounts:password_change_done')
    }, name='password_change'),
    url(r'^password/change/done/$', views.password_change_done, name='password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset, {
        'template_name': 'accounts/password_reset_form.html',
        'email_template_name': 'accounts/password_reset_email.html',
        'post_reset_redirect': reverse_lazy('accounts:password_reset_done')
    }, name='password_reset'),
    url(r'^password/reset/done', auth_views.password_reset_done, {
        'template_name': 'accounts/password_reset_done.html',
    }, name='password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {
            'template_name': 'accounts/password_reset_confirm.html',
            'post_reset_redirect': reverse_lazy('accounts:password_reset_complete')
        }, name='password_reset_confirm'),
    url(r'^password/reset/complete', views.password_reset_complete, name='password_reset_complete'),

    # account
    url(r'^edit$', views.ProfileUpdate.as_view(), name='edit'),
]

adventure_realm/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import notifications.urls
from .views import index

admin.autodiscover()

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^adventures/', include('adventures.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^notifications/', include(notifications.urls, namespace='notifications')),
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^(?P<username>[\w]+)/$', views.Detail.as_view(), name='detail')
]

accounts/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Follower(models.Model):
    email = models.EmailField(null=False)


class Profile(models.Model):
    user = models.OneToOneField(User)
    avatar_url = models.CharField(max_length=500, null=True, blank=True)
    avatar_file_name = models.CharField(max_length=500, null=True, blank=True)

accounts/forms.py
import re

from django import forms

from django.contrib.auth.models import User

from users.models import Profile
from registration.forms import RegistrationForm as BaseRegistrationForm


class RegistrationForm(BaseRegistrationForm):
    def clean(self):

        username_value = self.cleaned_data.get(User.USERNAME_FIELD)
        if username_value is not None:
            if not re.match(r'^[A-Za-z0-9]+$', username_value):
                self.add_error(User.USERNAME_FIELD, 'A username may only contain letters and numbers')

        super().clean()


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar_url', 'avatar_file_name']

accounts/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views import generic

from .forms import UserProfileForm


class ProfileUpdate(LoginRequiredMixin,
                    generic.UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'email']
    template_name = 'accounts/profile_update.html'

    def get_object(self, queryset=None):
        return User.objects.get(pk=self.request.user.pk)

    def get_success_url(self):
        messages.success(self.request, 'Your profile has been updated')
        return reverse('accounts:edit')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()

        context['user_profile_form'] = UserProfileForm()
        return context

@login_required
def password_change_done(request):
    messages.success(request, 'Your password has been changed')
    return redirect(reverse('accounts:password_change'))


def password_reset_complete(request):
    messages.success(request, 'Your password has been reset. Please log in with your new password')
    return redirect(reverse('accounts:login'))


# @login_required
# def avatar_upload(request, **kwargs):
#     if request.POST:
#         avatar_file = request.FILES.get('avatar')
#         user = request.user
#
#         s3_bucket = os.environ.get('S3_BUCKET')
#         s3_avatar_bucket_path = '%s/avatars/%s' % (user, avatar_file.name)
#         s3_avatar_file_path = 'https://s3-us-west-2.amazonaws.com/%s/%s' % (s3_bucket, s3_avatar_bucket_path)
#
#         form = UserProfileForm({
#             'avatar_url': s3_avatar_file_path,
#             'avatar_file_name': avatar_file.name
#         })
#
#         try:
#             form.instance.pk = user.profile.pk
#         except Profile.DoesNotExist:
#             """
#             By catching the error we can safely add the profile primary key when it exists. This will cause the view
#             to support inserting and updating the user's profile here
#             """
#             pass
#
#         form.instance.user = user
#
#         if form.is_valid():
#             form.save()
#
#             s3_client = boto3.client('s3')
#             s3_client.upload_fileobj(avatar_file, s3_bucket, s3_avatar_bucket_path, ExtraArgs={
#                 'ACL': 'public-read',
#                 'ContentType': avatar_file.content_type
#             })
#
#             messages.success(request, 'Profile photo uploaded')
#
#         return redirect(reverse('accounts:edit'))

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Log In{% endblock %}

{% block content %}
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    {% if form.errors %}
                        <div class="card-panel message message--error">Sorry, we weren't able to authenticate you with
                            the provided credentials
                        </div>
                    {% endif %}
                    <span class="card-title">Log In</span>

                    <form class="form" method="post" action="?next={{ next|default:"/" }}" autocomplete="off">
                        {% csrf_token %}
                        <div class="input-field">
                            <label for="id_username">Username</label>
                            {% render_field form.username %}
                            {{ form.username.errors }}
                        </div>
                        <div class="input-field">
                            <label for="id_password">Password</label>
                            {% render_field form.password %}
                            {{ form.password.errors }}
                        </div>
                        <button type="submit" class="btn btn-default">Log in</button>
                    </form>
                </div>
            </div>
            <p>If you don't have an account, you can <a href="{% url 'accounts:registration' %}">sign up</a> for one.
            </p>
            <a href="{% url 'accounts:password_reset' %}">forgot your password?</a>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "base.html" %}

{% block title %}Logged out{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-content">
            <span class="card-title">You've been logged out.</span>
            <p>Thanks for stopping by; when you come back, don't forget to <a href="{% url 'accounts:login' %}">log
                in</a> again.</p>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/navigation.html
<nav>
    <div class="nav-wrapper">
        <ul class="left">
            <li {% if active_link == 'profile' %}class="active"{% endif %}>
                <a href="{% url 'accounts:edit' %}">Public Profile</a>
            </li>
            <li {% if active_link == 'password' %}class="active"{% endif %}>
                <a href="{% url 'accounts:password_change' %}">Password</a>
            </li>
        </ul>
    </div>
</nav>

accounts/templates/accounts/password_change.html
{% extends "base.html" %}

{% block title %}Password Change{% endblock %}

{% block content %}
    {% include 'accounts/navigation.html' with active_link='password' %}
    <div class="card-panel">
        {% include 'accounts/password_change_form.html' %}
    </div>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% load widget_tweaks %}

<p>Please enter your old password, for security's sake, and then enter your new password twice so we can verify you
    typed it in correctly.</p>

<form action="" method="post">
    {% if form.errors %}
        <div class="card-panel message message--error">Please correct the errors below:</div>
    {% endif %}
    {% csrf_token %}
    <div class="input-field">
        <label for="id_old_password">Old password</label>
        {% render_field form.old_password %}
        {{ form.old_password.errors }}
    </div>
    <div class="input-field">
        <label for="id_new_password1">New password</label>
        {% render_field form.new_password1 %}
        {{ form.new_password1.errors }}
    </div>
    <div class="input-field">
        <label for="id_new_password2">Confirm password</label>
        {% render_field form.new_password2 %}
        {{ form.new_password2.errors }}
    </div>
    <button type="submit" class="btn btn-default">Change my password</button>
</form>

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Password reset complete' %}{% endblock %}

{% block content %}

    <div class="card">
        <div class="card-content">
            <span class="card-title">{% trans 'Password reset complete' %}</span>

            <p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

            <p>
                <a href="{% url 'accounts:login' %}">{% trans 'Log in' %}</a>
            </p>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans 'Password reset' %}{% endblock %}

{% block content %}
    {% if validlink %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">{% trans 'Enter new password' %}</span>
                <p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="input-field">
                        <label for="id_new_password1">New password</label>
                        {% render_field form.new_password1 %}
                        {{ form.new_password1.errors }}
                    </div>
                    <div class="input-field">
                        <label for="id_new_password2">Confirm password</label>
                        {% render_field form.new_password2 %}
                        {{ form.new_password2.errors }}
                    </div>
                    <button type="submit" class="btn btn-default">{% trans 'Change my password' %}</button>
                </form>
            </div>
        </div>
    {% else %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">{% trans 'Password reset unsuccessful' %}</span>
                <p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>
            </div>
        </div>
    {% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Password reset successful' %}{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-content">
            <span class="card-title">{% trans 'Password reset successful' %}</span>
            <p>{% trans "We've e-mailed you instructions for setting your password to the e-mail address you submitted. You should be receiving it shortly." %}</p>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}
{% autoescape off %}

    {% trans "You're receiving this e-mail because you requested a password reset" %}
    {% blocktrans %}for your user account at {{ site_name }}{% endblocktrans %}.

    {% trans "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}
    {% trans "Your username, in case you've forgotten:" %} {{ user.username }}

    {% trans "Thanks for using our site!" %}

    {% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans "Password reset" %}{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-content">
            <span class="card-title">{% trans "Password reset" %}</span>
            <p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll e-mail instructions for setting a new one." %}</p>
            <form action="" method="post">
                {% csrf_token %}
                <div class="input-field">
                    <label for="id_email">Email</label>
                    {% render_field form.email %}
                    {{ form.email.errors }}
                </div>
                <button type="submit" class="btn btn-default">{% trans 'Reset my password' %}</button>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile_form.html
{% load widget_tweaks %}

<form action="" method="post">
    {% if form.errors %}
        <div class="card-panel message message--error">Please correct the errors below:</div>
    {% endif %}

    {% csrf_token %}
    <div class="input-field">
        <label for="id_first_name">First Name</label>
        {% render_field form.first_name %}
        {{ form.first_name.errors }}
    </div>
    <div class="input-field">
        <label for="id_last_name">Last Name</label>
        {% render_field form.last_name %}
        {{ form.last_name.errors }}
    </div>
    <div class="input-field">
        <label for="id_email">Email</label>
        {% render_field form.email %}
        {{ form.email.errors }}
    </div>
    <button class="btn btn-default" type="submit">Save</button>
</form>

accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load avatar_image %}
{% load widget_tweaks %}

{% block title %}{{ user.username }} | Profile{% endblock %}

{% block content %}
    {% include 'accounts/navigation.html' with active_link='profile' %}
    <div class="card-panel">
        <div class="row">
            <div class="col m6 s12">
                {% include 'accounts/profile_form.html' %}
            </div>
            <div class="col m6 s12">
                {% avatar_image user size=200 %}
{#                <form action="{% url 'accounts:avatar_upload' %}" method="post" enctype="multipart/form-data">#}
{#                    {% csrf_token %}#}
{#                    <div class="file-field input-field">#}
{#                        <div class="btn btn-default">#}
{#                            <i class="material-icons left">add_a_photo</i>#}
{#                            <span>Image</span>#}
{#                            <input type="file" id="id_avatar" name="avatar" accept=".png, .jpg, .jpeg, .gif" required/>#}
{#                        </div>#}
{#                        <div class="file-path-wrapper">#}
{#                            <input class="file-path validate" type="text"/>#}
{#                        </div>#}
{#                        {{ user_profile_form.avatar.errors }}#}
{#                    </div>#}
{#                    <button class="btn btn-default">Upload</button>#}
{#                </form>#}
            </div>
        </div>
    </div>
{% endblock %}