accounts/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views
from registration.backends.simple import views as registration_views

from . import views
from . import forms

app_name = 'accounts'
urlpatterns = [
    # authentication
    url(r'^login', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout', auth_views.logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^registration', registration_views.RegistrationView.as_view(
        form_class=forms.RegistrationForm
    ), name='registration'),

    # password
    url(r'^password/change/$', auth_views.password_change, {
        'template_name': 'accounts/password_change.html',
        'post_change_redirect': reverse_lazy('accounts:password_change_done')
    }, name='password_change'),
    url(r'^password/change/done/$', views.password_change_done, name='password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset, {
        'template_name': 'accounts/password_reset_form.html',
        'email_template_name': 'accounts/password_reset_email.html',
        'post_reset_redirect': reverse_lazy('accounts:password_reset_done')
    }, name='password_reset'),
    url(r'^password/reset/done', auth_views.password_reset_done, {
        'template_name': 'accounts/password_reset_done.html',
    }, name='password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {
            'template_name': 'accounts/password_reset_confirm.html',
            'post_reset_redirect': reverse_lazy('accounts:password_reset_complete')
        }, name='password_reset_confirm'),
    url(r'^password/reset/complete', views.password_reset_complete, name='password_reset_complete'),

    # account
    url(r'^edit$', views.ProfileUpdate.as_view(), name='edit'),
]

adventure_realm/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import notifications.urls
from .views import index

admin.autodiscover()

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^adventures/', include('adventures.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^notifications/', include(notifications.urls, namespace='notifications')),
]

adventures/urls.py
from django.conf.urls import url

from . import views

app_name = 'adventures'
urlpatterns = [
    url(r'^$', views.AdventureIndex.as_view(), name='index'),
    url(r'^create$', views.AdventureCreate.as_view(), name='create'),
    url(r'^(?P<adventure_pk>[0-9]+)/update$', views.AdventureUpdate.as_view(), name='update'),

    # summary sentence
    url(r'^(?P<adventure_pk>[0-9]+)/summary-sentence/create', views.SummarySentenceCreate.as_view(),
        name='summary_sentence_create'),
    url(r'^(?P<adventure_pk>[0-9]+)/summary-sentence/(?P<summary_sentence_pk>[0-9]+)/update',
        views.SummarySentenceUpdate.as_view(),
        name='summary_sentence_update'),

    # summary paragraph
    url(r'^(?P<adventure_pk>[0-9]+)/summary-paragraph/create', views.SummaryParagraphCreate.as_view(),
        name='summary_paragraph_create'),
    url(r'^(?P<adventure_pk>[0-9]+)/summary-paragraph/(?P<summary_paragraph_pk>[0-9]+)/update',
        views.SummaryParagraphUpdate.as_view(),
        name='summary_paragraph_update'),

    # summary paragraph
    url(r'^(?P<adventure_pk>[0-9]+)/character-outline/create', views.CharacterOutlineCreate.as_view(),
        name='character_outline_create'),
    url(r'^(?P<adventure_pk>[0-9]+)/character-outline/(?P<character_outline_pk>[0-9]+)/update',
        views.CharacterOutlineUpdate.as_view(),
        name='character_outline_update'),
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^(?P<username>[\w]+)/$', views.Detail.as_view(), name='detail')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% include 'base_head.html' %}
</head>
<body>

{% include 'base_site_header.html' %}

<main class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                {{ message }}
                <a href="#!" class="right" title="close message"><i
                        class="material-icons message__close js-message-close">close</i></a>
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
</main>

{% include 'base_site_footer.html' %}
</body>
</html>

templates/base_account_links.html
{#<li>#}
{#    <a href="{% url 'users:detail' user.username %}">Your Profile</a>#}
{#</li>#}
{#<li>#}
{#    <a href="{% url 'users:songs' user.username %}">Your Songs</a>#}
{#</li>#}
{#<li>#}
{#    <a href="{% url 'users:contributions' user.username %}">Your Contributions</a>#}
{#</li>#}
{#<li>#}
{#    <a href="{% url 'users:track_requests' user.username %}">Your Track#}
{#        Requests</a>#}
{#</li>#}
<li>
    <a href="{% url 'accounts:edit' %}">Account Settings</a>
</li>
<li>
    <a href="{% url 'accounts:logout' %}">Log Out</a>
</li>

templates/base_head.html
{% load compile_static %}
{% load static %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
{#<link rel="stylesheet" href="{% static 'styles/main.less'|compile %}"/>#}
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

{% include 'base_meta.html' %}

templates/base_meta.html
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

templates/base_site_footer.html
{% load static %}

<footer id="SiteFooter" class="container" style="margin-top:100px;">
    <div class="navbar navbar-default">
        <div class="navbar-nav nav">
            <p class="navbar-text">© {% now "Y" %} Adventure Realm</p>
        </div>
    </div>
</footer>

templates/base_site_header.html
{% load avatar_image %}
{% load notifications_tags %}

<header class="site-header">
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">Adventure Realm</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'adventures:index' %}">Adventures</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.id %}
                        <li>
                            <a href="{% url 'adventures:create' %}">Create Adventure</a>
                        </li>
                        <li>
                            {% notifications_unread as unread_count %}
                            {% if  unread_count %}
                                <a href="{% url 'notifications:unread' %}">
                                    <span class="badge">{unread_count} messages</span>
                                </a>
                            {% else %}
                                <a href="{% url 'notifications:all' %}">
                                    messages
                                </a>
                            {% endif %}
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">
                                <span class="thumbnail"
                                      style="margin-bottom: 0;position: relative;top: 5px;margin-top: -10px;">
                                    {% avatar_image user size=25 %}
                                </span>
                            </a>

                            <ul class="dropdown-menu">
                                <li><a href="{% url 'accounts:edit' %}">Account Settings</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                            </ul>
                        </li>
                    {% else %}
                        {% include 'base_unauthenticated_links.html' %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/base_unauthenticated_links.html
<li>
    <a href="{% url 'accounts:registration' %}">Sign Up</a>
</li>
<li>
    <a href="{% url 'accounts:login' %}">Log In</a>
</li>