adventure_realm/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import notifications.urls
from .views import index

admin.autodiscover()

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^adventures/', include('adventures.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^notifications/', include(notifications.urls, namespace='notifications')),
]

adventures/urls.py
from django.conf.urls import url

from . import views

app_name = 'adventures'
urlpatterns = [
    url(r'^$', views.AdventureIndex.as_view(), name='index'),
    url(r'^create$', views.AdventureCreate.as_view(), name='create'),
    url(r'^(?P<adventure_pk>[0-9]+)/update$', views.AdventureUpdate.as_view(), name='update'),

    # summary sentence
    url(r'^(?P<adventure_pk>[0-9]+)/summary-sentence/create', views.SummarySentenceCreate.as_view(),
        name='summary_sentence_create'),
    url(r'^(?P<adventure_pk>[0-9]+)/summary-sentence/(?P<summary_sentence_pk>[0-9]+)/update',
        views.SummarySentenceUpdate.as_view(),
        name='summary_sentence_update'),

    # summary paragraph
    url(r'^(?P<adventure_pk>[0-9]+)/summary-paragraph/create', views.SummaryParagraphCreate.as_view(),
        name='summary_paragraph_create'),
    url(r'^(?P<adventure_pk>[0-9]+)/summary-paragraph/(?P<summary_paragraph_pk>[0-9]+)/update',
        views.SummaryParagraphUpdate.as_view(),
        name='summary_paragraph_update'),

    # summary paragraph
    url(r'^(?P<adventure_pk>[0-9]+)/character-outline/create', views.CharacterOutlineCreate.as_view(),
        name='character_outline_create'),
    url(r'^(?P<adventure_pk>[0-9]+)/character-outline/(?P<character_outline_pk>[0-9]+)/update',
        views.CharacterOutlineUpdate.as_view(),
        name='character_outline_update'),
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^(?P<username>[\w]+)/$', views.Detail.as_view(), name='detail')
]

adventures/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Adventure(models.Model):
    name = models.CharField(max_length=500)
    created_by = models.ForeignKey(User, blank=False, null=False, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class SummarySentence(models.Model):
    text = models.TextField(blank=False, null=False)
    adventure = models.OneToOneField(Adventure, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text


class SummaryParagraph(models.Model):
    text = models.TextField(blank=False, null=False)
    adventure = models.OneToOneField(Adventure, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text


class CharacterOutline(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    adventure = models.ForeignKey(Adventure, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    description = models.TextField(blank=False, null=False)
    background = models.TextField(blank=False, null=False)
    personality = models.TextField(blank=False, null=False)
    motive = models.TextField(blank=False, null=False)
    conflict = models.TextField(blank=False, null=False)
    image_url = models.CharField(max_length=1000, null=True, blank=True)

    def __str__(self):
        return self.name

adventures/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views import generic

from .models import Adventure, SummaryParagraph, SummarySentence, CharacterOutline
from .mixins import AdventureMixin, HasAccessToAdventure


class AdventureIndex(generic.ListView):
    model = Adventure
    context_object_name = 'adventure_list'


class AdventureCreate(generic.CreateView):
    model = Adventure
    fields = ['name']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'Adventure created')
        return reverse('adventures:update', kwargs={
            'adventure_pk': self.object.pk
        })


class AdventureUpdate(HasAccessToAdventure,
                      generic.UpdateView):
    model = Adventure
    pk_url_kwarg = 'adventure_pk'
    fields = ['name']

    def get_success_url(self):
        messages.success(self.request, 'Adventure updated')
        return reverse('adventures:update', kwargs={
            'adventure_pk': self.kwargs['adventure_pk']
        })


class SummarySentenceCreate(HasAccessToAdventure,
                            AdventureMixin,
                            generic.CreateView):
    model = SummarySentence
    fields = ['text']

    def form_valid(self, form):
        form.instance.adventure = Adventure.objects.get(pk=self.kwargs['adventure_pk'])
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'One Sentence Summary updated')
        return reverse('adventures:update', kwargs={
            'adventure_pk': self.kwargs['adventure_pk']
        })


class SummarySentenceUpdate(HasAccessToAdventure,
                            AdventureMixin,
                            generic.UpdateView):
    model = SummarySentence
    pk_url_kwarg = 'summary_sentence_pk'
    fields = ['text']

    def form_valid(self, form):
        form.instance.adventure = Adventure.objects.get(pk=self.kwargs['adventure_pk'])
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'One Sentence Summary updated')
        return reverse('adventures:update', kwargs={
            'adventure_pk': self.kwargs['adventure_pk']
        })


class SummaryParagraphCreate(HasAccessToAdventure,
                             AdventureMixin,
                             generic.CreateView):
    model = SummaryParagraph
    fields = ['text']

    def form_valid(self, form):
        form.instance.adventure = Adventure.objects.get(pk=self.kwargs['adventure_pk'])
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'One Paragraph Summary updated')
        return reverse('adventures:update', kwargs={
            'adventure_pk': self.kwargs['adventure_pk']
        })


class SummaryParagraphUpdate(HasAccessToAdventure,
                             AdventureMixin,
                             generic.UpdateView):
    model = SummaryParagraph
    pk_url_kwarg = 'summary_paragraph_pk'
    fields = ['text']

    def form_valid(self, form):
        form.instance.adventure = Adventure.objects.get(pk=self.kwargs['adventure_pk'])
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'One Paragraph Summary updated')
        return reverse('adventures:update', kwargs={
            'adventure_pk': self.kwargs['adventure_pk']
        })


class CharacterOutlineCreate(HasAccessToAdventure,
                             AdventureMixin,
                             generic.CreateView):
    model = CharacterOutline
    fields = ['name', 'image_url', 'description', 'background', 'personality', 'motive', 'conflict']

    def form_valid(self, form):
        form.instance.adventure = Adventure.objects.get(pk=self.kwargs['adventure_pk'])
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'Character Outline created')
        return reverse('adventures:update', kwargs={
            'adventure_pk': self.kwargs['adventure_pk']
        })


class CharacterOutlineUpdate(HasAccessToAdventure,
                             AdventureMixin,
                             generic.UpdateView):
    model = CharacterOutline
    pk_url_kwarg = 'character_outline_pk'
    fields = ['name', 'image_url', 'description', 'background', 'personality', 'motive', 'conflict']

    def form_valid(self, form):
        form.instance.adventure = Adventure.objects.get(pk=self.kwargs['adventure_pk'])
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'Character Outline updated')
        return reverse('adventures:update', kwargs={
            'adventure_pk': self.kwargs['adventure_pk']
        })

adventures/templates/adventures/adventure_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
    <form class="form-horizontal" action="" method="post">
        {% if form.errors %}
            <div class="alert alert-danger">Please correct the errors below:</div>
        {% endif %}

        {% csrf_token %}
        <div class="form-group">
            <div class="col-xs-12">
                <label for="id_name">Name</label>
                {% render_field form.name class+="form-control" %}
                {{ form.name.errors }}
            </div>
        </div>
        <button class="btn btn-primary" type="submit">Save</button>
    </form>

    {% if adventure %}
        <div class="adventure-story-steps">

            <div class="panel panel-default">
                <div class="panel-heading">
                    Summary Sentence

                    {% if adventure.summarysentence %}
                        <a class="btn btn-primary"
                           href="{% url 'adventures:summary_sentence_update' adventure.pk adventure.summarysentence.pk %}">Edit</a>
                    {% else %}
                        <a class="btn btn-primary"
                           href="{% url 'adventures:summary_sentence_create' adventure.pk %}">Create</a>
                    {% endif %}
                </div>
                <div class="panel-body">
                    <p>{{ adventure.summarysentence }}</p>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    Summary Paragraph

                    {% if adventure.summaryparagraph %}
                        <a class="btn btn-primary"
                           href="{% url 'adventures:summary_paragraph_update' adventure.pk adventure.summaryparagraph.pk %}">Edit</a>
                    {% else %}
                        <a class="btn btn-primary"
                           href="{% url 'adventures:summary_paragraph_create' adventure.pk %}">Create</a>
                    {% endif %}
                </div>
                <div class="panel-body">
                    <p>{{ adventure.summaryparagraph }}</p>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    Character Outlines
                    <a class="btn btn-primary" href="{% url 'adventures:character_outline_create' adventure.pk %}">Create</a>
                </div>
                <div class="panel-body">
                    <div class="row">
                        {% for character_outline in adventure.characteroutline_set.all %}
                            <div class="col-sm-6 col-md-4">
                                <div class="thumbnail">
                                    <div style="height: 250px; overflow: hidden">
                                        <img class="img-responsive" src="{{ character_outline.image_url }}"
                                         alt="{{ character_outline.name }}">
                                    </div>
                                    <div class="caption">
                                        <h3>{{ character_outline.name }}</h3>
                                        <p>{{ character_outline.description|truncatechars:100 }}</p>
                                        <a href="{% url 'adventures:character_outline_update' adventure.pk character_outline.pk %}"
                                           class="btn btn-primary" role="button">Edit</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

adventures/templates/adventures/adventure_list.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Adventures{% endblock %}

{% block content %}
    <h1 class="page-header">Adventures</h1>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="media-list">
                {% for adventure in adventure_list %}
                    <div class="media">
                        <div class="media-left media-middle">
                            <a href="{% url 'adventures:update' adventure.pk %}">
                                <img class="media-object" width="150px"
                                     src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkmTNki_2SEoNJlt1ZcvqGEHHnsTtaaAdJSD_u5Kl3-Xibn3r3">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">
                                <a href="{% url 'adventures:update' adventure.pk %}">{{ adventure.name }}</a>
                            </h4>

                            <p>{{ adventure.summarysentence }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

adventures/templates/adventures/characteroutline_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'adventures:update' adventure.pk %}">{{ adventure.name }}</a></li>
        <li class="active">Character Outline</li>
    </ol>

    <div class="row">
        <form class="form-horizontal col-xs-12 col-sm-6" action="" method="post">
            {% if form.errors %}
                <div class="alert alert-danger">Please correct the errors below:</div>
            {% endif %}

            {% csrf_token %}
            <div class="form-group">
                <div class="col-xs-12 col-sm-6">
                    <label for="id_name">Name</label>
                    {% render_field form.name class+="form-control" %}
                    {{ form.name.errors }}
                </div>
                <div class="col-xs-12 col-sm-6">
                    <label for="id_name">Image Url</label>
                    {% render_field form.image_url class+="form-control" %}
                    {{ form.namimage_url.errors }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-xs-12">
                    <label for="id_description">Description</label>
                    {% render_field form.description class+="form-control" %}
                    {{ form.description.errors }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-xs-12">
                    <label for="id_background">Background</label>
                    {% render_field form.background class+="form-control" %}
                    {{ form.background.errors }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-xs-12">
                    <label for="id_personality">Personality</label>
                    {% render_field form.personality class+="form-control" %}
                    {{ form.personality.errors }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-xs-12">
                    <label for="id_motive">Motive</label>
                    {% render_field form.motive class+="form-control" %}
                    {{ form.motive.errors }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-xs-12">
                    <label for="id_conflict">Conflict</label>
                    {% render_field form.conflict class+="form-control" %}
                    {{ form.conflict.errors }}
                </div>
            </div>

            <button class="btn btn-primary" type="submit">Save</button>
        </form>
        <div class="col-xs-12 col-sm-6">
            {% if form.image_url.value %}
                <img class="img-thumbnail" style="max-height:300px" src="{{ form.image_url.value }}"
                     alt="{{ form.name.value }}"/>
            {% else %}
                <div class="thumbnail" style="height: 300px; width: 100%;">
                    <div style="background: #ececec; width:100%; height: 100%;">
                        <i style="font-size: 40px;top: 50%;left: 50%;margin-top: -20px;margin-left: -20px;"
                           class="glyphicon glyphicon-camera"></i>
                    </div>
                </div>
            {% endif %}
            <h2>{{ form.name.value }}</h2>

            <h4>Description</h4>
            <p>{{ form.description.value }}</p>

            <h4>Background</h4>
            <p>{{ form.background.value }}</p>

            <h4>Personality</h4>
            <p>{{ form.description.value }}</p>

            <h4>Motive</h4>
            <p>{{ form.motive.value }}</p>

            <h4>Conflict</h4>
            <p>{{ form.conflict.value }}</p>
        </div>
    </div>
{% endblock %}

adventures/templates/adventures/summaryparagraph_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'adventures:update' adventure.pk %}">{{ adventure.name }}</a></li>
        <li class="active">Summary Paragraph</li>
    </ol>

    <form class="form-horizontal" action="" method="post">
        {% if form.errors %}
            <div class="alert alert-danger">Please correct the errors below:</div>
        {% endif %}

        {% csrf_token %}
        <div class="form-group">
            <div class="col-xs-12">
                <label for="id_text">One Paragraph Summary</label>
                {% render_field form.text class+="form-control" %}
                {{ form.text.errors }}
            </div>
        </div>

        <button class="btn btn-primary" type="submit">Save</button>
    </form>
{% endblock %}

adventures/templates/adventures/summarysentence_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'adventures:update' adventure.pk %}">{{ adventure.name }}</a></li>
        <li class="active">Summary Sentence</li>
    </ol>

    <form class="form-horizontal" action="" method="post">
        {% if form.errors %}
            <div class="alert alert-danger">Please correct the errors below:</div>
        {% endif %}

        {% csrf_token %}
        <div class="form-group">
            <div class="col-xs-12">
                <label for="id_text">One Sentence Summary</label>
                {% render_field form.text class+="form-control" %}
                {{ form.text.errors }}
            </div>
        </div>

        <button class="btn btn-primary" type="submit">Save</button>
    </form>
{% endblock %}